
export class User {
  appName: string = ""
  deviceModel: string = "HARMONY"
  deviceType: string = "PHONE"
  password: string = ""
  sign: string = ""
  type: number = 0
  username: string = ""
  uuid: string = ""
  email: string = ""
  nickname: string = ""
  updateTime: string = ""
  vipExpireTime: string = ""
  avatar: string = ""
  wxUnionId: string = ""
  vipExpireTimeStr: string = ""
  rid: string = ""
}